//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rehapitation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int ID { get; set; }
        public double DEBT { get; set; }
        public double NSBUD { get; set; }
        public double NSAUD { get; set; }
        public double TRFAS { get; set; }
        public double ADEAT { get; set; }
        public int PatientFK { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
